name: Import crDroid Kernel at Specific Commit

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  import:
    runs-on: ubuntu-latest

    steps:

      - name: Clone source repo FULL
        run: |
          git clone https://github.com/crdroidandroid/android_kernel_oneplus_sm8150.git source
          cd source

      - name: Push specific commit to YOUR repo branch 16.0
        run: |
          cd source

          git config user.name "beingsk"
          git config user.email "actions@github.com"

          # Add your repo as remote
          git remote add target https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/beingsk5/crdroid.git

          # Push specific commit as branch 16.0
          git push target e3558992e2a9334924354c88728698247175f289:refs/heads/16.0 --force
